[pytest]
testpaths = tests
pythonpath = src
addopts = -v --tb=short
filterwarnings =
    ignore:SelectableGroups dict interface is deprecated:DeprecationWarning:opentelemetry.util._importlib_metadata
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::pydantic.warnings.PydanticDeprecatedSince212
