apiVersion: 1

datasources:
  - name: Postgres
    uid: metlife_pg
    type: postgres
    access: proxy
    url: ${GRAFANA_DB_HOST}:${GRAFANA_DB_PORT}
    user: ${GRAFANA_DB_USER}
    database: ${GRAFANA_DB_NAME}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
